=begin
Project name: Beacon Resources
Description: BeaconResources is a web application that will allow for easy access to verified resources, such as homeless shelters and food banks, by county in New Jersey with appropriate category filtering.
Filename: admin.rb
Description: Model for admins generated by Devise
Last modified on: 11/11/2020
=end

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  # Removed registerable as admin should be selected and inserted into the code manually
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end
